AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  GoUpdateStatistics:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: GoUpdateStatistics/lambda_function.lambda_handler
      MemorySize: 512
      Role: 'arn:aws:iam::828201240123:role/LambdaRole_UpdateStatistics'
      Runtime: python3.6
      Timeout: 60
