AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  GoNotificationSystem:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: GoNotificationSystem/lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::828201240123:role/LambdaRole_GoNotificationSystem'
      Runtime: python3.6
      Timeout: 15
